#ifndef CONFIG_H
#define CONFIG_H

enum {
    MIN_NUMBER_OF_FIRST_WORKERS  = 1,
    MIN_NUMBER_OF_SECOND_WORKERS = 1,
    MIN_NUMBER_OF_THIRD_WORKERS  = 1,
    MAX_NUMBER_OF_FIRST_WORKERS  = 3,
    MAX_NUMBER_OF_SECOND_WORKERS = 5,
    MAX_NUMBER_OF_THIRD_WORKERS  = 2,
};

enum {
    MIN_SLEEP_TIME = 1,
    MAX_SLEEP_TIME = 9,
};

#endif
